FROM alpine:3.23.2

LABEL maintainer="Michael Oberdorf IT-Consulting <info@oberdorf-itc.de>"
LABEL site.local.program.version="1.4.1"

RUN apk upgrade --available --no-cache --update \
    && apk add --no-cache --update \
       python3=3.12.12-r0 \
       py3-pip=25.1.1-r1 \
    # Cleanup APK
    && rm -rf /var/cache/apk/* /tmp/* /var/tmp/*

COPY --chown=root:root /src /
COPY --chown=root:root /examples/test.json /test.json

RUN pip3 install --no-cache-dir -r /requirements.txt --break-system-packages

EXPOSE 5020/tcp
EXPOSE 5020/udp

USER 1434:1434

# Start Server
ENTRYPOINT ["python", "-u", "/app/modbus_server.py"]
