name: build-container-image
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
jobs:
  container-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
     - name: Checkout GIT repository
       uses: actions/checkout@v3
     - name: Get the application version
       id: application-version
       run: |
         image_version=$(grep "^LABEL site.local.program.version=" Dockerfile | cut -d= -f2 | sed -e 's/"//g')
         if [ -z "${image_version}" ]; then
           echo "ERROR: unable to detect version number!" >&2
           exit 1
         fi
         echo "tag=${image_version}" >> $GITHUB_OUTPUT
     - name: Build container image
       run: |
         docker build . --file Dockerfile --tag oitc/modbus-server:${{steps.application-version.outputs.tag}}
     - name: Export container image for caching
       run: |
         docker save --output oitc-modbus-server_${{steps.application-version.outputs.tag}}.tar oitc/modbus-server:${{steps.application-version.outputs.tag}}

     - name: Upload the container image for caching
       uses: actions/upload-artifact@v3.1.2
       with:
         name: modbus-server
         path: oitc-modbus-server_${{steps.application-version.outputs.tag}}.tar
         if-no-files-found: error
         retention-days: 1
