name:  container-image-build-validation
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
jobs:
  container-image-build-validation:
    uses: cybcon/github_workflows/.github/workflows/container-image-build-validation.yaml@v2.1.0
